DROP TABLE attraktions_entfernung;
DROP TABLE anzahlung;
DROP TABLE buchung;
DROP TABLE kunde;
DROP TABLE bild;
DROP TABLE beinhaltete_ausstattung;
DROP TABLE ausstattung;
DROP TABLE ferienwohnung;
DROP TABLE attraktion;
DROP TABLE adresse;
DROP TABLE land;

CREATE TABLE land (
    laendername VARCHAR2(30) NOT NULL,
    CONSTRAINT laendername_pk PRIMARY KEY (laendername)
);

CREATE TABLE adresse (
    adress_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    strasse VARCHAR2(40) NOT NULL,
    hausnummer CHAR(5) NOT NULL,
    postleitzahl INT NOT NULL,
    stadt VARCHAR2(40) NOT NULL,
    laendername VARCHAR2(30) NOT NULL,
    CONSTRAINT adress_id_pk PRIMARY KEY (adress_id),
    CONSTRAINT land_fk FOREIGN KEY (laendername) 
        REFERENCES land (laendername)
);

CREATE TABLE attraktion (
    attraktionsname VARCHAR2(40) NOT NULL,
    attraktionsbeschreibung VARCHAR2(80),
    CONSTRAINT attraktionsname_pk PRIMARY KEY (attraktionsname)
);

CREATE TABLE ferienwohnung (
    wohnungsname VARCHAR2(40) NOT NULL,
    zimmer INT NOT NULL CHECK (zimmer > 0),
    groesse FLOAT NOT NULL CHECK (groesse > 0),
    preis FLOAT NOT NULL CHECK (preis > 0),
    wohnungs_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    adress_id NUMBER,
    CONSTRAINT wohnungs_pk PRIMARY KEY (wohnungs_id),
    CONSTRAINT adress_wohnungs_fk FOREIGN KEY (adress_id) 
        REFERENCES adresse (adress_id)
);

CREATE TABLE ausstattung (
    ausstattungsname VARCHAR2(40) NOT NULL,
    CONSTRAINT ausstattungs_pk PRIMARY KEY (ausstattungsname)
);

CREATE TABLE beinhaltete_ausstattung (
    wohnungs_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ausstattungsname VARCHAR2(40) NOT NULL,
    CONSTRAINT wohnungs_id_fk FOREIGN KEY (wohnungs_id) 
        REFERENCES ferienwohnung (wohnungs_id)
        ON DELETE CASCADE,
    CONSTRAINT ausstattungsname_fk FOREIGN KEY (ausstattungsname) 
        REFERENCES ausstattung (ausstattungsname)
        ON DELETE CASCADE
);

CREATE TABLE bild (
    bildlink VARCHAR2(100) NOT NULL,
    wohnungs_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CONSTRAINT wohnungs_bild_fk FOREIGN KEY (wohnungs_id) 
        REFERENCES ferienwohnung (wohnungs_id)
        ON DELETE CASCADE
);

CREATE TABLE kunde (
    mail VARCHAR2(35) NOT NULL CHECK (mail LIKE '%@%.%'),
    passwort VARCHAR2(30) NOT NULL,
    kundenname VARCHAR2(40) NOT NULL CHECK (kundenname LIKE '% %'),
    iban CHAR(22) NOT NULL,
    adress_id NUMBER,
    CONSTRAINT mail_pk PRIMARY KEY (mail),
    CONSTRAINT adress_kunden_fk FOREIGN KEY (adress_id) 
        REFERENCES adresse (adress_id)
);

CREATE TABLE buchung (
    buchungsnummer NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    startdatum DATE NOT NULL,
    enddatum DATE NOT NULL,
    stornodatum DATE,
    rechnungsnummer INT,
    rechnungsdatum DATE,
    betrag FLOAT,
    bewertungsdatum DATE,
    bewertungssterne INT CHECK (bewertungssterne BETWEEN 1 AND 5),
    wohnungs_id NUMBER,
    mail VARCHAR2(35) NOT NULL,
    CONSTRAINT buchungsnummer_pk PRIMARY KEY (buchungsnummer),
    CONSTRAINT wohnungs_buchungs_fk FOREIGN KEY (wohnungs_id) 
        REFERENCES ferienwohnung (wohnungs_id),
    CONSTRAINT mail_buchungs_fk FOREIGN KEY (mail) 
        REFERENCES kunde (mail),
    CONSTRAINT start_vor_ende CHECK (startdatum < enddatum),
    CONSTRAINT bewertung_nach_ende CHECK (bewertungsdatum > enddatum)
);

CREATE TABLE anzahlung (
    anzahlungs_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    geldbetrag FLOAT NOT NULL,
    zahlungsdatum DATE NOT NULL,
    buchungsnummer NUMBER,
    CONSTRAINT anzahlungs_pk PRIMARY KEY (anzahlungs_id),
    CONSTRAINT buchungsnummer_anzahlung_fk FOREIGN KEY (buchungsnummer) 
        REFERENCES buchung (buchungsnummer)
        ON DELETE CASCADE
);

CREATE TABLE attraktions_entfernung (
    wohnungs_id NUMBER,
    attraktionsname VARCHAR2(40),
    kilometer FLOAT CHECK (kilometer < 50),
    CONSTRAINT wohnungs_entfernungs_fk FOREIGN KEY (wohnungs_id) 
        REFERENCES ferienwohnung (wohnungs_id)
        ON DELETE CASCADE,
    CONSTRAINT attraktionsname_entfernungs_fk FOREIGN KEY (attraktionsname) 
        REFERENCES attraktion (attraktionsname)
        ON DELETE CASCADE
);

GRANT INSERT, SELECT, UPDATE ON adresse TO DBSYS49;
GRANT INSERT, SELECT ON anzahlung TO DBSYS49;
GRANT SELECT ON attraktion TO DBSYS49;
GRANT SELECT ON attraktions_entfernung TO DBSYS49;
GRANT INSERT, SELECT, UPDATE ON buchung TO DBSYS49;
GRANT INSERT, SELECT, UPDATE ON ferienwohnung TO DBSYS49;
GRANT INSERT, SELECT, UPDATE, DELETE ON beinhaltete_ausstattung TO DBSYS49;
GRANT SELECT ON ausstattung TO DBSYS49;
GRANT INSERT, SELECT, UPDATE ON kunde TO DBSYS49;
GRANT INSERT, SELECT, UPDATE, DELETE on bild TO DBSYS49;