SET TRANSACTION READ WRITE;
begin

INSERT INTO ausstattung (ausstattungsname) VALUES ('Sauna');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Pool');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Jacuzzi');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Balcony');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Terrace');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Garden');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Barbecue');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Fireplace');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Air Conditioning');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Heating');
INSERT INTO ausstattung (ausstattungsname) VALUES ('TV');
INSERT INTO ausstattung (ausstattungsname) VALUES ('WiFi');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Kitchen');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Fridge');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Oven');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Microwave');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Coffee Machine');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Dishwasher');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Washing Machine');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Dryer');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Iron');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Hairdryer');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Towels');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Bed Linen');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Toiletries');
INSERT INTO ausstattung (ausstattungsname) VALUES ('First Aid Kit');
INSERT INTO ausstattung (ausstattungsname) VALUES ('Fire Extinguisher');
commit;
end;