SET TRANSACTION READ WRITE;
begin

INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (1, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (1, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (1, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (2, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (2, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (2, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (2, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (3, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (3, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (4, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (5, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (5, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (5, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (6, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (7, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (7, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (7, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (7, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (7, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (8, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (8, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (9, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (9, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (9, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (9, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (9, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (10, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (10, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (10, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (11, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (12, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (13, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (13, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (14, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (14, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (14, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (14, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (14, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (15, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (15, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (15, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (15, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (15, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (16, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (16, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (17, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (17, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (17, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (17, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (18, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (19, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (20, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (20, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (20, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (20, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (21, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (22, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (22, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (23, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (23, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (23, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (24, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (25, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (25, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (26, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (26, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (26, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (26, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (27, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (27, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (27, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (27, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (27, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (28, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (28, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (28, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (28, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (28, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (29, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (29, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (29, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (29, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (30, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (31, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (31, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (31, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (31, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (31, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (32, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (32, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (32, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (32, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (33, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (34, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (34, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (34, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (35, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (35, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (35, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (35, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (36, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (36, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (36, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (36, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (37, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (37, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (38, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (38, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (38, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (39, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (39, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (39, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (39, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (40, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (40, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (41, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (41, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (41, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (41, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (42, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (42, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (43, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (44, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (45, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (45, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (45, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (45, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (45, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (46, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (46, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (47, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (47, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (47, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (47, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (47, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (48, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (48, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (48, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (48, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (49, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (49, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (49, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (50, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (50, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (51, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (51, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (52, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (52, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (52, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (52, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (52, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (53, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (53, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (53, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (54, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (54, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (54, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (54, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (55, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (55, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (55, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (56, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (56, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (56, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (56, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (57, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (57, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (58, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (58, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (58, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (58, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (58, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (59, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (60, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (61, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (61, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (61, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (62, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (62, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (63, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (63, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (63, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (64, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (64, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (64, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (64, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (65, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (65, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (65, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (65, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (66, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (66, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (66, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (66, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (67, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (67, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (67, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (68, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (68, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (68, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (69, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (69, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (69, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (69, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (69, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (70, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (70, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (71, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (71, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (71, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (72, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (72, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (72, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (72, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (72, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (73, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (73, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (73, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (74, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (74, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (74, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (74, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (74, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (75, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (75, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (75, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (76, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (76, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (76, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (76, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (77, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (77, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (77, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (77, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (77, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (78, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (78, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (78, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (78, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (79, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (80, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (80, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (81, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (81, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (82, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (82, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (83, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (83, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (84, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (84, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (84, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (84, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (85, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (86, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (86, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (86, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (86, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (86, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (87, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (87, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (87, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (87, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (88, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (88, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (88, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (88, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (89, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (89, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (89, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (89, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (90, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (90, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (90, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (91, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (91, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (92, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (92, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (93, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (93, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (93, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (94, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (94, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (94, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (94, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (95, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (95, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (95, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (95, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (96, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (96, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (96, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (97, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (97, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (97, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (97, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (97, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (98, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (98, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (98, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (98, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (99, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (99, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (100, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (100, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (100, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (100, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (100, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (101, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (102, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (103, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (103, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (103, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (103, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (103, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (104, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (104, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (104, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (104, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (105, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (105, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (105, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (106, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (107, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (107, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (107, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (107, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (108, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (108, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (108, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (108, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (109, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (110, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (110, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (110, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (111, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (112, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (112, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (112, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (112, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (112, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (113, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (113, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (113, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (114, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (114, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (114, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (114, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (115, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (115, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (116, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (116, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (116, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (117, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (117, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (117, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (118, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (118, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (118, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (119, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (119, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (119, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (119, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (120, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (120, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (120, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (120, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (120, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (121, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (121, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (121, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (121, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (122, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (123, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (123, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (123, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (124, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (124, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (125, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (125, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (125, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (125, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (126, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (126, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (126, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (127, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (127, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (127, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (128, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (128, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (128, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (129, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (129, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (129, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (129, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (130, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (130, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (130, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (130, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (131, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (131, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (131, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (131, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (132, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (132, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (132, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (132, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (132, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (133, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (133, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (133, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (134, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (135, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (135, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (135, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (135, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (136, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (136, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (136, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (137, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (137, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (137, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (137, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (138, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (138, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (139, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (139, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (139, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (139, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (140, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (141, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (141, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (141, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (141, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (142, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (142, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (142, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (142, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (143, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (144, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (145, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (145, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (145, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (146, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (146, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (146, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (146, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (147, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (147, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (147, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (147, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (147, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (148, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (148, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (148, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (148, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (149, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (150, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (150, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (150, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (151, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (151, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (151, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (151, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (152, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (153, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (153, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (153, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (153, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (153, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (154, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (155, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (155, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (155, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (155, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (156, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (157, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (157, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (157, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (158, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (158, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (158, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (158, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (159, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (159, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (159, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (159, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (159, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (160, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (160, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (160, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (160, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (161, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (161, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (162, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (162, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (162, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (162, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (162, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (163, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (163, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (163, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (164, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (164, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (164, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (164, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (165, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (165, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (165, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (165, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (165, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (166, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (166, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (167, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (167, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (168, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (168, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (168, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (169, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (169, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (169, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (169, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (170, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (170, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (170, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (170, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (171, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (172, 'Dryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (172, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (172, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (172, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (173, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (173, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (174, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (174, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (174, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (175, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (175, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (175, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (175, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (175, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (176, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (176, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (176, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (177, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (177, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (178, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (178, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (178, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (178, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (178, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (179, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (179, 'First Aid Kit');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (180, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (180, 'Dishwasher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (181, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (182, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (182, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (182, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (182, 'Fireplace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (182, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (183, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (183, 'Heating');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (183, 'Barbecue');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (183, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (184, 'TV');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (185, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (185, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (185, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (185, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (186, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (187, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (187, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (188, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (188, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (189, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (189, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (189, 'Towels');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (189, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (189, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (190, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (190, 'Bed Linen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (190, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (190, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (190, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (191, 'Pool');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (191, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (192, 'WiFi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (193, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (193, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (194, 'Balcony');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (194, 'Toiletries');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (195, 'Sauna');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (196, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (196, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (196, 'Kitchen');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (196, 'Microwave');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (196, 'Garden');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (197, 'Air Conditioning');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (197, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (197, 'Hairdryer');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (198, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (198, 'Oven');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (198, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (198, 'Fire Extinguisher');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (199, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (199, 'Fridge');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (199, 'Jacuzzi');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (199, 'Washing Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (200, 'Terrace');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (200, 'Iron');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (200, 'Coffee Machine');
INSERT INTO beinhaltete_ausstattung (wohnungs_id, ausstattungsname) VALUES (200, 'Towels');
commit;
end;