SET TRANSACTION READ WRITE;
begin

INSERT INTO attraktion (attraktionsname) VALUES ('Museum');
INSERT INTO attraktion (attraktionsname) VALUES ('Zoo');
INSERT INTO attraktion (attraktionsname) VALUES ('Aquarium');
INSERT INTO attraktion (attraktionsname) VALUES ('Amusement Park');
INSERT INTO attraktion (attraktionsname) VALUES ('Theme Park');
INSERT INTO attraktion (attraktionsname) VALUES ('Water Park');
INSERT INTO attraktion (attraktionsname) VALUES ('Botanical Garden');
INSERT INTO attraktion (attraktionsname) VALUES ('National Park');
INSERT INTO attraktion (attraktionsname) VALUES ('Nature Reserve');
INSERT INTO attraktion (attraktionsname) VALUES ('Sculpture Park');
INSERT INTO attraktion (attraktionsname) VALUES ('Wildlife Sanctuary');
INSERT INTO attraktion (attraktionsname) VALUES ('Observatory');
INSERT INTO attraktion (attraktionsname) VALUES ('Planetarium');
INSERT INTO attraktion (attraktionsname) VALUES ('Science Center');
INSERT INTO attraktion (attraktionsname) VALUES ('Art Gallery');
INSERT INTO attraktion (attraktionsname) VALUES ('Historic Site');
INSERT INTO attraktion (attraktionsname) VALUES ('Monument');
INSERT INTO attraktion (attraktionsname) VALUES ('Castle');
INSERT INTO attraktion (attraktionsname) VALUES ('Palace');
INSERT INTO attraktion (attraktionsname) VALUES ('Fortress');
INSERT INTO attraktion (attraktionsname) VALUES ('Tower');
INSERT INTO attraktion (attraktionsname) VALUES ('Keep');
INSERT INTO attraktion (attraktionsname) VALUES ('Citadel');
INSERT INTO attraktion (attraktionsname) VALUES ('Stronghold');
INSERT INTO attraktion (attraktionsname) VALUES ('Bastion');
INSERT INTO attraktion (attraktionsname) VALUES ('Rampart');
INSERT INTO attraktion (attraktionsname) VALUES ('Moat');
INSERT INTO attraktion (attraktionsname) VALUES ('Bailey');
INSERT INTO attraktion (attraktionsname) VALUES ('Donjon');
INSERT INTO attraktion (attraktionsname) VALUES ('Barbican');
INSERT INTO attraktion (attraktionsname) VALUES ('Curtain Wall');
INSERT INTO attraktion (attraktionsname) VALUES ('Gatehouse');
INSERT INTO attraktion (attraktionsname) VALUES ('Portcullis');
INSERT INTO attraktion (attraktionsname) VALUES ('Drawbridge');
INSERT INTO attraktion (attraktionsname) VALUES ('Machicolation');
INSERT INTO attraktion (attraktionsname) VALUES ('Battlement');
INSERT INTO attraktion (attraktionsname) VALUES ('Arrow');
INSERT INTO attraktion (attraktionsname) VALUES ('Slit');
INSERT INTO attraktion (attraktionsname) VALUES ('Turret');
INSERT INTO attraktion (attraktionsname) VALUES ('Merlon');
INSERT INTO attraktion (attraktionsname) VALUES ('Parapet');
INSERT INTO attraktion (attraktionsname) VALUES ('Crenel');
INSERT INTO attraktion (attraktionsname) VALUES ('Embrasure');
INSERT INTO attraktion (attraktionsname) VALUES ('Sally Port');
INSERT INTO attraktion (attraktionsname) VALUES ('Ravelin');
INSERT INTO attraktion (attraktionsname) VALUES ('Counterscarp');
INSERT INTO attraktion (attraktionsname) VALUES ('Scarp');
INSERT INTO attraktion (attraktionsname) VALUES ('Glacis');
INSERT INTO attraktion (attraktionsname) VALUES ('Fosse');
INSERT INTO attraktion (attraktionsname) VALUES ('Escarpment');
INSERT INTO attraktion (attraktionsname) VALUES ('Redoubt');
INSERT INTO attraktion (attraktionsname) VALUES ('Bulwark');
INSERT INTO attraktion (attraktionsname) VALUES ('Hornwork');
INSERT INTO attraktion (attraktionsname) VALUES ('Sconce');
INSERT INTO attraktion (attraktionsname) VALUES ('Caponier');
INSERT INTO attraktion (attraktionsname) VALUES ('Counterguard');
INSERT INTO attraktion (attraktionsname) VALUES ('Tenaille');
INSERT INTO attraktion (attraktionsname) VALUES ('Lunette');
INSERT INTO attraktion (attraktionsname) VALUES ('Redan');
commit;
end;