SET TRANSACTION READ WRITE;
begin

INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (1, 'Keep', 8);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (1, 'Rampart', 45);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (1, 'Sally Port', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (1, 'Planetarium', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (1, 'Ravelin', 28);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (2, 'Water Park', 31);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (2, 'Fosse', 29);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (2, 'Slit', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (2, 'Citadel', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (2, 'Zoo', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (3, 'Redoubt', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (4, 'Wildlife Sanctuary', 42);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (4, 'Amusement Park', 23);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (5, 'Slit', 31);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (5, 'Donjon', 37);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (5, 'Battlement', 48);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (5, 'Counterscarp', 30);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (6, 'Historic Site', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (7, 'Caponier', 48);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (7, 'Sculpture Park', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (7, 'Zoo', 26);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (8, 'Bailey', 15);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (8, 'Glacis', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (8, 'Keep', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (8, 'Slit', 9);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (9, 'Redan', 39);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (9, 'Bailey', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (9, 'Arrow', 7);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (9, 'Barbican', 7);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (9, 'Fortress', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (10, 'Slit', 31);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (10, 'Theme Park', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (10, 'Embrasure', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (10, 'Donjon', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (11, 'Redan', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (11, 'Caponier', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (11, 'Water Park', 44);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (12, 'Sconce', 30);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (13, 'National Park', 29);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (13, 'Portcullis', 42);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (13, 'Drawbridge', 6);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (14, 'Lunette', 44);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (14, 'Amusement Park', 30);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (14, 'Counterguard', 40);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (14, 'Counterscarp', 15);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (14, 'Escarpment', 49);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (15, 'Amusement Park', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (15, 'Museum', 49);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (15, 'Redan', 40);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (16, 'Parapet', 24);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (17, 'Theme Park', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (17, 'Bailey', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (18, 'Glacis', 43);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (18, 'Historic Site', 40);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (18, 'Hornwork', 48);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (18, 'Moat', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (19, 'Sally Port', 42);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (19, 'Sconce', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (19, 'Observatory', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (20, 'Redoubt', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (20, 'Tenaille', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (20, 'Drawbridge', 45);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (20, 'Merlon', 48);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (20, 'Historic Site', 33);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (21, 'Fortress', 3);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (22, 'Art Gallery', 49);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (22, 'Stronghold', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (22, 'Nature Reserve', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (22, 'Machicolation', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (22, 'Redan', 9);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (23, 'Monument', 38);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (23, 'Parapet', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (23, 'Art Gallery', 43);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (23, 'Sconce', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (24, 'Hornwork', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (25, 'Escarpment', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (25, 'Donjon', 33);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (25, 'Theme Park', 44);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (25, 'Tower', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (26, 'Rampart', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (26, 'Aquarium', 47);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (26, 'Barbican', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (26, 'Wildlife Sanctuary', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (26, 'Sculpture Park', 7);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (27, 'Moat', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (27, 'Fortress', 40);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (27, 'Escarpment', 30);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (28, 'Wildlife Sanctuary', 37);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (28, 'Palace', 13);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (28, 'Nature Reserve', 43);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (28, 'Amusement Park', 26);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (29, 'Planetarium', 45);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (29, 'Aquarium', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (30, 'Castle', 3);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (31, 'Monument', 26);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (31, 'Hornwork', 26);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (31, 'Sconce', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (31, 'Ravelin', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (32, 'Parapet', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (32, 'Wildlife Sanctuary', 33);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (32, 'Monument', 40);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (33, 'Parapet', 13);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (33, 'Curtain Wall', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (33, 'Arrow', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (34, 'Merlon', 17);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (34, 'Gatehouse', 15);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (35, 'Drawbridge', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (36, 'Glacis', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (36, 'Tenaille', 5);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (37, 'Tower', 17);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (37, 'Monument', 43);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (38, 'Redan', 26);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (39, 'Sconce', 6);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (40, 'Battlement', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (40, 'Tenaille', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (40, 'Zoo', 13);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (41, 'Observatory', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (41, 'Stronghold', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (42, 'Bastion', 43);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (42, 'Amusement Park', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (42, 'Battlement', 8);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (42, 'Wildlife Sanctuary', 39);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (42, 'Water Park', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (43, 'Wildlife Sanctuary', 49);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (44, 'Redoubt', 24);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (44, 'Ravelin', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (45, 'Castle', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (45, 'Amusement Park', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (46, 'Tower', 24);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (47, 'Citadel', 9);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (47, 'Amusement Park', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (47, 'Tenaille', 43);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (47, 'Historic Site', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (48, 'Redan', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (48, 'Citadel', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (48, 'Merlon', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (48, 'Glacis', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (48, 'Aquarium', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (49, 'Donjon', 6);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (49, 'Palace', 18);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (49, 'Portcullis', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (49, 'Sculpture Park', 32);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (49, 'Museum', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (50, 'Lunette', 47);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (50, 'Redoubt', 14);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (50, 'Water Park', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (50, 'Stronghold', 23);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (51, 'Museum', 14);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (51, 'Slit', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (51, 'Redan', 3);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (51, 'Keep', 5);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (52, 'Science Center', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (52, 'Embrasure', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (52, 'Nature Reserve', 28);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (52, 'Planetarium', 14);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (53, 'Slit', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (53, 'Sculpture Park', 14);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (53, 'Zoo', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (53, 'Counterguard', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (54, 'Keep', 8);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (54, 'Aquarium', 40);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (54, 'Escarpment', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (54, 'Fosse', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (54, 'Gatehouse', 48);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (55, 'Water Park', 13);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (56, 'Counterguard', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (56, 'Bastion', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (57, 'Theme Park', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (57, 'Scarp', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (58, 'Caponier', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (58, 'Donjon', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (58, 'Redan', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (59, 'Theme Park', 29);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (59, 'Gatehouse', 17);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (59, 'Barbican', 49);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (60, 'Redoubt', 39);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (60, 'Sconce', 41);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (61, 'Redan', 31);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (62, 'Glacis', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (62, 'Theme Park', 26);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (63, 'Machicolation', 41);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (63, 'Moat', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (63, 'Parapet', 7);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (63, 'Counterscarp', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (63, 'Tenaille', 8);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (64, 'Observatory', 14);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (64, 'Scarp', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (65, 'Counterscarp', 44);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (65, 'Sconce', 33);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (65, 'Bulwark', 5);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (65, 'Zoo', 44);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (66, 'Redan', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (66, 'Nature Reserve', 39);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (67, 'Turret', 47);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (67, 'Escarpment', 17);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (67, 'Embrasure', 49);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (67, 'Sconce', 30);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (68, 'Arrow', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (69, 'Fortress', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (69, 'Tenaille', 9);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (70, 'Tower', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (70, 'Rampart', 26);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (71, 'Bastion', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (71, 'Caponier', 38);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (71, 'Zoo', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (71, 'Lunette', 9);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (72, 'Observatory', 24);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (73, 'Palace', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (73, 'Curtain Wall', 32);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (73, 'Fortress', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (73, 'Rampart', 9);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (73, 'Botanical Garden', 44);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (74, 'Portcullis', 38);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (74, 'Counterscarp', 44);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (74, 'Ravelin', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (74, 'National Park', 11);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (74, 'Palace', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (75, 'Counterscarp', 13);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (75, 'Ravelin', 6);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (75, 'Fortress', 32);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (76, 'Parapet', 11);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (76, 'Nature Reserve', 26);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (76, 'Turret', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (76, 'Bastion', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (76, 'Botanical Garden', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (77, 'Nature Reserve', 15);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (77, 'Machicolation', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (77, 'Amusement Park', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (77, 'Ravelin', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (78, 'Lunette', 30);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (78, 'Botanical Garden', 5);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (79, 'Wildlife Sanctuary', 41);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (79, 'Amusement Park', 38);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (79, 'Hornwork', 13);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (80, 'Tower', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (80, 'Moat', 28);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (80, 'Hornwork', 30);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (80, 'Bastion', 6);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (81, 'Turret', 43);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (82, 'Historic Site', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (82, 'Keep', 41);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (83, 'Crenel', 31);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (83, 'Science Center', 28);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (83, 'Tower', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (83, 'Bailey', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (84, 'Keep', 8);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (84, 'Redan', 31);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (85, 'National Park', 24);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (85, 'Ravelin', 42);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (86, 'Fosse', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (86, 'Water Park', 5);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (86, 'Castle', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (86, 'Fortress', 24);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (87, 'Sculpture Park', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (87, 'Slit', 24);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (87, 'Arrow', 37);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (87, 'Battlement', 3);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (88, 'Sculpture Park', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (88, 'Historic Site', 3);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (88, 'Slit', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (88, 'Glacis', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (88, 'Tower', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (89, 'Sally Port', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (89, 'Gatehouse', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (89, 'Historic Site', 15);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (89, 'Amusement Park', 28);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (90, 'Aquarium', 39);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (90, 'Zoo', 7);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (90, 'Art Gallery', 15);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (90, 'Science Center', 43);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (90, 'Counterscarp', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (91, 'Bulwark', 7);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (91, 'Aquarium', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (91, 'Parapet', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (92, 'Ravelin', 5);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (92, 'Tower', 43);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (92, 'Palace', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (92, 'Zoo', 31);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (92, 'Caponier', 13);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (93, 'Gatehouse', 3);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (93, 'Monument', 30);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (93, 'Turret', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (93, 'Counterscarp', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (94, 'Merlon', 8);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (94, 'Bulwark', 38);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (94, 'Moat', 6);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (94, 'Crenel', 3);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (94, 'Embrasure', 39);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (95, 'Amusement Park', 31);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (95, 'Observatory', 38);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (96, 'Turret', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (96, 'Citadel', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (96, 'Crenel', 47);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (97, 'Lunette', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (97, 'Ravelin', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (97, 'Rampart', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (97, 'Science Center', 3);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (97, 'Embrasure', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (98, 'Botanical Garden', 6);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (98, 'Sally Port', 38);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (98, 'Rampart', 28);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (98, 'Observatory', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (99, 'Art Gallery', 29);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (99, 'Amusement Park', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (99, 'Rampart', 30);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (100, 'Science Center', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (100, 'Caponier', 11);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (100, 'Gatehouse', 33);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (101, 'Planetarium', 45);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (102, 'Art Gallery', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (102, 'Slit', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (102, 'Rampart', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (102, 'Fortress', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (102, 'Keep', 28);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (103, 'Portcullis', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (104, 'Amusement Park', 37);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (104, 'Donjon', 23);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (105, 'Turret', 28);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (105, 'Redan', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (106, 'Battlement', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (106, 'Escarpment', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (107, 'Glacis', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (107, 'Palace', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (108, 'Escarpment', 41);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (108, 'Caponier', 45);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (108, 'Nature Reserve', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (108, 'Donjon', 49);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (108, 'Fortress', 18);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (109, 'Embrasure', 40);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (110, 'Lunette', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (110, 'Merlon', 15);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (110, 'Scarp', 23);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (110, 'Bulwark', 14);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (110, 'Redan', 49);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (111, 'Water Park', 32);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (112, 'Hornwork', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (112, 'Bulwark', 17);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (112, 'Science Center', 41);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (113, 'Parapet', 5);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (114, 'Botanical Garden', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (115, 'Arrow', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (115, 'Tenaille', 40);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (115, 'Planetarium', 28);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (115, 'Barbican', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (115, 'Wildlife Sanctuary', 23);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (116, 'Art Gallery', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (116, 'Wildlife Sanctuary', 17);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (116, 'Historic Site', 47);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (116, 'Escarpment', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (116, 'Stronghold', 48);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (117, 'Zoo', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (118, 'Art Gallery', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (118, 'Sally Port', 26);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (118, 'Museum', 42);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (119, 'Water Park', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (119, 'Zoo', 37);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (120, 'Stronghold', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (120, 'Parapet', 14);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (120, 'Bulwark', 23);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (121, 'Historic Site', 44);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (121, 'Embrasure', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (121, 'Barbican', 40);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (121, 'Moat', 23);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (121, 'Rampart', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (122, 'Observatory', 39);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (123, 'Palace', 28);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (124, 'Aquarium', 15);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (124, 'Donjon', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (124, 'Turret', 32);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (124, 'Monument', 15);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (125, 'Wildlife Sanctuary', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (125, 'Bailey', 29);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (126, 'Fortress', 8);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (126, 'Redoubt', 39);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (127, 'Merlon', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (127, 'Water Park', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (127, 'Crenel', 38);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (127, 'Portcullis', 49);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (128, 'Fosse', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (128, 'Glacis', 14);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (128, 'Citadel', 11);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (129, 'Turret', 5);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (129, 'Aquarium', 26);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (129, 'Counterguard', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (129, 'Scarp', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (130, 'Nature Reserve', 24);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (130, 'Embrasure', 30);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (130, 'Machicolation', 43);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (130, 'Counterscarp', 49);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (130, 'Battlement', 11);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (131, 'Drawbridge', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (131, 'Counterscarp', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (131, 'Slit', 14);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (131, 'Crenel', 48);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (132, 'Drawbridge', 18);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (132, 'Bailey', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (132, 'Monument', 45);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (132, 'Keep', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (132, 'Battlement', 31);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (133, 'Science Center', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (133, 'Ravelin', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (133, 'Redoubt', 13);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (133, 'Nature Reserve', 18);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (134, 'Bastion', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (134, 'Parapet', 43);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (134, 'Merlon', 48);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (135, 'Stronghold', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (135, 'Tenaille', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (136, 'Theme Park', 24);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (136, 'Curtain Wall', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (136, 'Crenel', 33);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (136, 'Sculpture Park', 45);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (136, 'Scarp', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (137, 'Turret', 14);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (137, 'Merlon', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (137, 'Caponier', 3);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (138, 'Redan', 31);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (138, 'Portcullis', 18);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (139, 'Gatehouse', 6);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (140, 'Tower', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (140, 'Slit', 17);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (140, 'Rampart', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (141, 'Slit', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (141, 'Redan', 49);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (142, 'Monument', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (142, 'Bastion', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (142, 'Botanical Garden', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (142, 'Caponier', 44);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (142, 'Stronghold', 28);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (143, 'Planetarium', 15);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (144, 'Crenel', 3);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (144, 'Botanical Garden', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (144, 'Redoubt', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (144, 'Fosse', 3);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (145, 'Ravelin', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (145, 'Bailey', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (146, 'Fortress', 31);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (146, 'Bailey', 47);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (147, 'Caponier', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (147, 'Portcullis', 42);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (148, 'Observatory', 18);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (148, 'Amusement Park', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (148, 'Escarpment', 24);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (148, 'Counterguard', 30);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (148, 'Bastion', 7);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (149, 'Fortress', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (149, 'Tower', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (150, 'Gatehouse', 5);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (150, 'Stronghold', 23);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (150, 'Arrow', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (150, 'Moat', 26);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (150, 'Merlon', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (151, 'Donjon', 42);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (151, 'Amusement Park', 40);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (152, 'Stronghold', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (152, 'Slit', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (152, 'Observatory', 38);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (152, 'Ravelin', 37);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (153, 'Counterscarp', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (153, 'Turret', 33);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (153, 'Curtain Wall', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (153, 'Escarpment', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (154, 'Fortress', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (154, 'Escarpment', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (155, 'Planetarium', 44);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (155, 'Water Park', 9);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (155, 'Barbican', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (156, 'Arrow', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (156, 'Art Gallery', 32);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (157, 'Donjon', 33);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (157, 'Water Park', 37);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (157, 'Science Center', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (158, 'Redan', 44);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (158, 'Water Park', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (158, 'Lunette', 3);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (159, 'Merlon', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (160, 'Arrow', 33);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (160, 'Parapet', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (160, 'Wildlife Sanctuary', 29);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (160, 'Sally Port', 9);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (161, 'Nature Reserve', 17);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (161, 'Turret', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (162, 'Counterguard', 8);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (162, 'Wildlife Sanctuary', 40);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (163, 'Merlon', 48);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (163, 'Donjon', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (163, 'Redoubt', 18);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (163, 'Sally Port', 41);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (163, 'Crenel', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (164, 'Science Center', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (165, 'Nature Reserve', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (165, 'Crenel', 29);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (165, 'Tower', 17);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (166, 'Sally Port', 33);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (167, 'Caponier', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (167, 'Parapet', 2);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (168, 'Slit', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (168, 'Rampart', 49);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (169, 'Bastion', 17);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (169, 'Redoubt', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (169, 'Sculpture Park', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (170, 'Scarp', 47);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (170, 'Sconce', 9);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (170, 'Redoubt', 41);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (171, 'Wildlife Sanctuary', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (171, 'Botanical Garden', 49);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (171, 'Art Gallery', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (171, 'Tenaille', 18);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (171, 'Redan', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (172, 'Tenaille', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (173, 'Planetarium', 44);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (173, 'Tenaille', 9);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (173, 'Battlement', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (174, 'Castle', 47);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (174, 'Hornwork', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (174, 'Water Park', 14);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (175, 'Embrasure', 36);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (175, 'Counterscarp', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (175, 'Nature Reserve', 38);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (175, 'Water Park', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (175, 'Amusement Park', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (176, 'Barbican', 25);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (176, 'Battlement', 45);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (176, 'Citadel', 44);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (176, 'Tenaille', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (176, 'Art Gallery', 45);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (177, 'Moat', 22);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (177, 'Theme Park', 14);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (178, 'Water Park', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (178, 'Nature Reserve', 24);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (178, 'Embrasure', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (178, 'Sculpture Park', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (179, 'Escarpment', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (179, 'Botanical Garden', 14);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (179, 'Fosse', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (180, 'Historic Site', 38);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (180, 'Caponier', 38);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (181, 'Counterguard', 24);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (182, 'Observatory', 15);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (182, 'Counterscarp', 15);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (182, 'Scarp', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (182, 'Donjon', 8);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (183, 'Drawbridge', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (183, 'Bulwark', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (183, 'Museum', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (184, 'Parapet', 28);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (184, 'Arrow', 6);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (184, 'Historic Site', 5);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (184, 'Art Gallery', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (184, 'Scarp', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (185, 'Glacis', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (185, 'Barbican', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (185, 'Bastion', 16);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (185, 'Theme Park', 43);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (186, 'Portcullis', 21);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (186, 'Aquarium', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (186, 'Scarp', 1);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (186, 'Caponier', 5);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (187, 'Stronghold', 45);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (187, 'Caponier', 5);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (187, 'National Park', 17);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (188, 'Bulwark', 47);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (188, 'Redan', 7);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (188, 'Historic Site', 33);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (188, 'Portcullis', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (189, 'Counterscarp', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (190, 'Battlement', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (190, 'Observatory', 35);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (190, 'Stronghold', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (190, 'Citadel', 34);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (190, 'Hornwork', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (191, 'Wildlife Sanctuary', 48);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (191, 'Nature Reserve', 33);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (191, 'Machicolation', 30);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (191, 'Planetarium', 4);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (191, 'Historic Site', 40);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (192, 'Fosse', 24);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (192, 'Castle', 5);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (192, 'Portcullis', 29);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (193, 'Embrasure', 7);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (193, 'Sculpture Park', 27);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (194, 'Castle', 11);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (194, 'Moat', 8);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (194, 'Barbican', 10);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (194, 'Theme Park', 8);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (194, 'Sally Port', 29);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (195, 'Bailey', 29);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (195, 'Escarpment', 20);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (195, 'Wildlife Sanctuary', 43);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (195, 'Sconce', 17);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (196, 'Counterguard', 30);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (197, 'Rampart', 48);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (197, 'Sculpture Park', 12);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (198, 'Embrasure', 19);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (199, 'Ravelin', 41);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (199, 'Museum', 46);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (199, 'Parapet', 37);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (199, 'Drawbridge', 38);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (199, 'Bulwark', 8);
INSERT INTO attraktions_entfernung (wohnungs_id, attraktionsname, kilometer) VALUES (200, 'Aquarium', 13);
commit;
end;